import NavbarComponent from "@/components/NavBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CartProvider } from "./context/CartContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Online Food Ordering App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-200 container mx-auto`}>
        <CartProvider>
          {<NavbarComponent />}
          <div>
            {children}
          </div>
          </CartProvider>
      </body>
    </html>
  );
}
